import Head from "next/head";
import Intro from "/components/Intro";
import Card from "/components/Card";
import AboutMePicture from "../components/AboutMePicture";
import ContactBubble from "../components/ContactBubble";
import ContactForm from "../components/ContactForm";

export default function Home() {
  return (
    <div>
      <div className="container h-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <nav className="header-left">
          <span className="corner-name">Javier Rodriguez</span>
          <div className="header-right">
            <h3>Projects</h3>
            <h3>About</h3>
            <h3>Contact</h3>
          </div>
        </nav>

        <Intro></Intro>
      </div>

      <section className="project-section">
        <div className="container">
          <h2>Projects</h2>
          <div className="card-section">
            <Card></Card>
            <Card></Card>
            <Card></Card>
            <Card></Card>
          </div>
        </div>
      </section>

      <section className="about-me-section">
        <AboutMePicture></AboutMePicture>
        <div className="about-me-text">
          <h2>About Me</h2>
          <p>
            This is some example text that will be going in the about me section
            that is to be used to help me figure out the spacing of the
            paragraph.
          </p>
        </div>
      </section>

      <section className="contact-section">
        <div className="contact-section-body">
          <span className="interest">
            Are You Interested? <br></br> Say Hi!
          </span>
          <ContactBubble></ContactBubble>
        </div>
        <ContactForm></ContactForm>
      </section>
    </div>
  );
}
